[package]
name = "varint-simd"
version = "0.1.0"
authors = ["Andrew Sun <me@andrewsun.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
criterion = "0.3"
integer-encoding = "2.1"
rand = "0.8"

[[bench]]
name = "varint_bench"
harness = false
